name: Dev Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - release_for: Windows-x86_64
            target: x86_64-pc-windows-msvc
            bin: yarm.exe
            name: yarm-windows-x86_64.exe
          - release_for: Windows-x86
            target: i686-pc-windows-msvc
            bin: yarm.exe
            name: yarm-windows-x86.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Rename Artifact
        shell: pwsh
        run: |
          Copy-Item -Path "target\${{ matrix.platform.target }}\release\${{ matrix.platform.bin }}" -Destination "${{ matrix.platform.name }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: ${{ matrix.platform.name }}
          retention-days: 1

  publish-dev:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Generate Release Notes
        shell: pwsh
        run: |
          $date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          $commit = git log -1 --format='%h - %s (%an)'
          @"
          ### ðŸ›  Latest Development Build

          Built from branch ``master`` at $date UTC

          #### Latest Commit
          $commit
          "@ | Out-File -FilePath release_notes.md -Encoding utf8

      - name: Release Dev
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev
          name: Development Build
          body_path: release_notes.md
          prerelease: true
          files: |
            yarm-windows-x86_64.exe
            yarm-windows-x86.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
